---
swagger: "2.0"
info:
  description: "CC Project - Panacea"
  version: "1.0.0"
  title: "Panacea"
host: "exlg9bsuba.execute-api.us-west-2.amazonaws.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /panacea:
    post:
      operationId: "sendMessage"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "SendRequest"
        required: true
        schema:
          $ref: "#/definitions/SendRequest"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/SentResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "500":
          description: "500 response"
          schema:
            $ref: "#/definitions/Error"
        "403":
          description: "403 response"
          schema:
            $ref: "#/definitions/Error"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
definitions:
  SendRequest:
    type: "object"
    properties:
      messages:
        type: "string"
  Message:
    type: "object"
    properties:
      type:
        type: "string"
      unstructured:
        $ref: "#/definitions/UnstructuredMessage"
  UnstructuredMessage:
    type: "object"
    properties:
      id:
        type: "string"
      text:
        type: "string"
      timestamp:
        type: "string"
        format: "datetime"
  SentResponse:
    type: "object"
    properties:
      messages:
        type: "array"
        items:
          $ref: "#/definitions/Message"
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"